import type { StructureUnit } from "@/lib/types";

export const structureCatalog: StructureUnit[] = [
  {
    key: "articles",
    title: "Articles",
    family: "Accuracy",
    description: "Use a, an, and the with clearer noun phrases.",
    skillArea: "grammar",
    baseLevel: "A2",
    supportObjective: "Improve noun phrase accuracy.",
  },
  {
    key: "present-perfect",
    title: "Present Perfect",
    family: "Tenses",
    description: "Connect past actions to present meaning.",
    skillArea: "grammar",
    baseLevel: "B1",
    supportObjective: "Control tense consistency.",
  },
  {
    key: "past-vs-present-perfect",
    title: "Past vs Present Perfect",
    family: "Tenses",
    description: "Choose between finished time and present relevance.",
    skillArea: "grammar",
    baseLevel: "B1",
    supportObjective: "Reduce tense confusion.",
  },
  {
    key: "prepositions",
    title: "Prepositions",
    family: "Accuracy",
    description: "Use natural preposition choices in common contexts.",
    skillArea: "grammar",
    baseLevel: "A2",
    supportObjective: "Fix frequent phrasing slips.",
  },
  {
    key: "modals",
    title: "Modals",
    family: "Control",
    description: "Express certainty, advice, and obligation precisely.",
    skillArea: "grammar",
    baseLevel: "B1",
    supportObjective: "Increase control over tone.",
  },
  {
    key: "conditionals",
    title: "Conditionals",
    family: "Complexity",
    description: "Build hypothetical meaning with clear structure.",
    skillArea: "sentence_building",
    baseLevel: "B2",
    supportObjective: "Expand flexible sentence building.",
  },
  {
    key: "relative-clauses",
    title: "Relative Clauses",
    family: "Complexity",
    description: "Attach extra detail without breaking flow.",
    skillArea: "sentence_building",
    baseLevel: "B2",
    supportObjective: "Combine ideas smoothly.",
  },
  {
    key: "connectors",
    title: "Connectors",
    family: "Flow",
    description: "Link ideas with although, however, because, and while.",
    skillArea: "sentence_building",
    baseLevel: "B1",
    supportObjective: "Improve coherence.",
  },
  {
    key: "sentence-combining",
    title: "Sentence Combining",
    family: "Flow",
    description: "Turn short basic clauses into richer sentences.",
    skillArea: "sentence_building",
    baseLevel: "B1",
    supportObjective: "Raise sentence complexity.",
  },
  {
    key: "passive-voice",
    title: "Passive Voice",
    family: "Form",
    description: "Shift focus to result or receiver when needed.",
    skillArea: "grammar",
    baseLevel: "B2",
    supportObjective: "Handle more formal structures.",
  },
  {
    key: "hedging",
    title: "Hedging",
    family: "Register",
    description: "Sound precise and careful in opinions and argument.",
    skillArea: "vocabulary",
    baseLevel: "C1",
    supportObjective: "Improve nuance and academic tone.",
  },
  {
    key: "collocations",
    title: "Collocations",
    family: "Vocabulary in Use",
    description: "Choose words that naturally belong together.",
    skillArea: "vocabulary",
    baseLevel: "B1",
    supportObjective: "Sound more natural.",
  },
];

export function getStructureUnit(structureKey: string) {
  return structureCatalog.find((unit) => unit.key === structureKey);
}
