import type { BuilderKind, StructureUnit } from "@/lib/types";

export const builderMeta: Record<
  BuilderKind,
  {
    title: string;
    shortTitle: string;
    description: string;
  }
> = {
  grammar: {
    title: "Grammar Builder",
    shortTitle: "Grammar",
    description: "Refresh rules, see them in context, then produce clean sentences until the pattern becomes usable.",
  },
  vocabulary: {
    title: "Vocabulary Builder",
    shortTitle: "Vocabulary",
    description: "Learn words through meaning, register, collocation, and repeated use instead of isolated memorization.",
  },
  phrase_idiom: {
    title: "Phrase & Idiom Builder",
    shortTitle: "Phrases",
    description: "Train natural chunks, academic phrases, spoken expressions, and idioms through real production.",
  },
  sentence: {
    title: "Sentence Builder",
    shortTitle: "Sentence",
    description: "Turn short ideas into flexible, natural, and more advanced sentences under guided pressure.",
  },
};

export const structureCatalog: StructureUnit[] = [
  {
    key: "articles",
    title: "Articles",
    family: "Accuracy",
    description: "Use a, an, and the with clearer noun phrases.",
    skillArea: "grammar",
    builderKind: "grammar",
    baseLevel: "A2",
    supportObjective: "Improve noun phrase accuracy.",
    categoryPath: ["Grammar", "Accuracy"],
    teachingSummary: "Articles show whether a noun is new, specific, or general.",
    whenToUse: "Use articles before singular countable nouns and before specific shared references.",
    whenNotToUse: "Do not force articles before uncountable or plural nouns when you mean them generally.",
    examples: [
      "I bought a book from the shop near the station.",
      "The desk in my room is next to a window.",
      "Advice can be useful, even without an article.",
    ],
    commonMistakes: [
      "Dropping the article before a singular noun.",
      "Using the with a noun that is new information.",
      "Adding an article before uncountable nouns like advice.",
    ],
    prerequisiteKeys: [],
    relatedKeys: ["prepositions", "word-order"],
  },
  {
    key: "prepositions",
    title: "Prepositions",
    family: "Accuracy",
    description: "Use natural preposition choices in common contexts.",
    skillArea: "grammar",
    builderKind: "grammar",
    baseLevel: "A2",
    supportObjective: "Fix frequent phrasing slips.",
    categoryPath: ["Grammar", "Accuracy"],
    teachingSummary: "Prepositions often follow usage patterns rather than logic, so repetition matters.",
    whenToUse: "Use them to mark time, movement, place, relationships, and fixed verb patterns.",
    whenNotToUse: "Do not translate prepositions word-for-word from your first language.",
    examples: [
      "She arrived at the office before nine.",
      "I am interested in the course.",
      "We talked about the plan on the way home.",
    ],
    commonMistakes: [
      "Choosing the wrong preposition after a common adjective.",
      "Using in instead of at for a point location.",
      "Adding an unnecessary preposition after a verb.",
    ],
    prerequisiteKeys: [],
    relatedKeys: ["articles", "collocations"],
  },
  {
    key: "present-perfect",
    title: "Present Perfect",
    family: "Tenses",
    description: "Connect past actions to present meaning.",
    skillArea: "grammar",
    builderKind: "grammar",
    baseLevel: "B1",
    supportObjective: "Control tense consistency.",
    categoryPath: ["Grammar", "Tenses"],
    teachingSummary: "Present perfect connects what happened before with what matters now.",
    whenToUse: "Use it for life experience, unfinished time, or a present result from a past action.",
    whenNotToUse: "Avoid it with finished-time markers like yesterday or last night.",
    examples: [
      "I have improved my speaking confidence this year.",
      "She has already gone to the meeting.",
      "We have lived here for three years.",
    ],
    commonMistakes: [
      "Using simple past with unfinished time.",
      "Using went instead of gone after has or have.",
      "Forgetting the auxiliary have or has.",
    ],
    prerequisiteKeys: [],
    relatedKeys: ["past-vs-present-perfect", "modals"],
  },
  {
    key: "past-vs-present-perfect",
    title: "Past vs Present Perfect",
    family: "Tenses",
    description: "Choose between finished time and present relevance.",
    skillArea: "grammar",
    builderKind: "grammar",
    baseLevel: "B1",
    supportObjective: "Reduce tense confusion.",
    categoryPath: ["Grammar", "Tenses"],
    teachingSummary: "The choice depends on whether the time is finished or still connected to now.",
    whenToUse: "Use simple past with finished time markers and present perfect with present relevance.",
    whenNotToUse: "Do not mix present perfect with explicit finished-time phrases like yesterday.",
    examples: [
      "I saw her yesterday.",
      "I have never tried that restaurant.",
      "We finished the task last night.",
    ],
    commonMistakes: [
      "Using have seen yesterday.",
      "Choosing simple past for life experience up to now.",
      "Switching tense mid-idea without a time shift.",
    ],
    prerequisiteKeys: ["present-perfect"],
    relatedKeys: ["present-perfect", "reported-speech"],
  },
  {
    key: "modals",
    title: "Modals",
    family: "Control",
    description: "Express certainty, advice, and obligation precisely.",
    skillArea: "grammar",
    builderKind: "grammar",
    baseLevel: "B1",
    supportObjective: "Increase control over tone.",
    categoryPath: ["Grammar", "Control"],
    teachingSummary: "Modals change certainty and social tone without changing the core action.",
    whenToUse: "Use them to soften advice, signal possibility, or express obligation and deduction.",
    whenNotToUse: "Do not stack multiple modals or use should where certainty is too strong.",
    examples: [
      "You might want to check the final section again.",
      "This could be a stronger opening.",
      "The result must be wrong if the input changed.",
    ],
    commonMistakes: [
      "Using infinitive forms incorrectly after a modal.",
      "Choosing must where might is more realistic.",
      "Forgetting that modals are followed by the base verb.",
    ],
    prerequisiteKeys: [],
    relatedKeys: ["hedging", "soften-a-claim"],
  },
  {
    key: "conditionals",
    title: "Conditionals",
    family: "Complexity",
    description: "Build hypothetical meaning with clear structure.",
    skillArea: "sentence_building",
    builderKind: "grammar",
    baseLevel: "B2",
    supportObjective: "Expand flexible sentence building.",
    categoryPath: ["Grammar", "Complexity"],
    teachingSummary: "Conditionals link conditions and results to talk about routines, possibilities, and unreal situations.",
    whenToUse: "Use them when one idea depends on another.",
    whenNotToUse: "Do not force will in both clauses unless the meaning truly requires it.",
    examples: [
      "If you practice every day, you improve more steadily.",
      "If I had more time, I would take the evening course.",
      "If the team had checked the draft, the mistake might have disappeared earlier.",
    ],
    commonMistakes: [
      "Using will after if in routine conditionals.",
      "Mixing second and third conditional forms accidentally.",
      "Leaving the condition and result disconnected.",
    ],
    prerequisiteKeys: ["connectors"],
    relatedKeys: ["sentence-combining", "cause-and-effect"],
  },
  {
    key: "passive-voice",
    title: "Passive Voice",
    family: "Form",
    description: "Shift focus to result or receiver when needed.",
    skillArea: "grammar",
    builderKind: "grammar",
    baseLevel: "B2",
    supportObjective: "Handle more formal structures.",
    categoryPath: ["Grammar", "Form"],
    teachingSummary: "Passive voice moves attention from the doer to the action or result.",
    whenToUse: "Use it when the result matters more than the agent or the agent is unknown.",
    whenNotToUse: "Avoid it when an active sentence would be clearer and more direct.",
    examples: [
      "The final draft was approved yesterday.",
      "Several changes have been suggested by the reviewer.",
      "This issue should be addressed before launch.",
    ],
    commonMistakes: [
      "Forgetting the correct be form.",
      "Using the base verb instead of the past participle.",
      "Choosing passive when the sentence needs a clear subject.",
    ],
    prerequisiteKeys: ["present-perfect"],
    relatedKeys: ["reported-speech", "academic-phrases"],
  },
  {
    key: "relative-clauses",
    title: "Relative Clauses",
    family: "Complexity",
    description: "Attach extra detail without breaking flow.",
    skillArea: "sentence_building",
    builderKind: "grammar",
    baseLevel: "B2",
    supportObjective: "Combine ideas smoothly.",
    categoryPath: ["Grammar", "Complexity"],
    teachingSummary: "Relative clauses let you add detail while keeping ideas in one sentence.",
    whenToUse: "Use them to define people, things, places, or to add non-essential extra detail.",
    whenNotToUse: "Do not force them when two short sentences would be clearer.",
    examples: [
      "The course that I took last month was far more practical than expected.",
      "My manager, who rarely gives long feedback, highlighted the same issue twice.",
      "This is the point where the argument becomes weaker.",
    ],
    commonMistakes: [
      "Using the wrong relative pronoun.",
      "Dropping commas in non-defining clauses.",
      "Building a clause that breaks sentence clarity.",
    ],
    prerequisiteKeys: ["connectors", "sentence-combining"],
    relatedKeys: ["sentence-combining", "compare-contrast"],
  },
  {
    key: "reported-speech",
    title: "Reported Speech",
    family: "Form",
    description: "Retell what someone said with natural tense control.",
    skillArea: "grammar",
    builderKind: "grammar",
    baseLevel: "B2",
    supportObjective: "Control tense shifts in reporting.",
    categoryPath: ["Grammar", "Form"],
    teachingSummary: "Reported speech changes viewpoint and often changes tense, pronouns, and time markers.",
    whenToUse: "Use it when summarizing what others said or wrote.",
    whenNotToUse: "Do not backshift automatically when the fact is still true and current.",
    examples: [
      "She said that the timeline was too optimistic.",
      "The teacher told us that clarity matters more than length.",
      "He asked whether the final version had already been sent.",
    ],
    commonMistakes: [
      "Keeping direct-speech time words like tomorrow without adjusting them.",
      "Backshifting when the meaning is still present and universal.",
      "Mixing told and said with the wrong structure.",
    ],
    prerequisiteKeys: ["past-vs-present-perfect"],
    relatedKeys: ["passive-voice", "modals"],
  },
  {
    key: "connectors",
    title: "Connectors",
    family: "Flow",
    description: "Link ideas with although, however, because, and while.",
    skillArea: "sentence_building",
    builderKind: "grammar",
    baseLevel: "B1",
    supportObjective: "Improve coherence.",
    categoryPath: ["Grammar", "Flow"],
    teachingSummary: "Connectors shape logic by showing reason, contrast, time, or result.",
    whenToUse: "Use them when your sentence needs a visible relationship between ideas.",
    whenNotToUse: "Do not stack too many connectors in one sentence or overuse because for every relation.",
    examples: [
      "Although the draft was clear, it still sounded too direct.",
      "I stayed late because the last section needed work.",
      "The idea is strong; however, the evidence is still thin.",
    ],
    commonMistakes: [
      "Using a spoken connector in an academic sentence.",
      "Forgetting punctuation around however.",
      "Choosing the wrong logical relation between two clauses.",
    ],
    prerequisiteKeys: [],
    relatedKeys: ["sentence-combining", "compare-contrast", "cause-and-effect"],
  },
  {
    key: "word-order",
    title: "Word Order",
    family: "Accuracy",
    description: "Place key sentence parts where English expects them.",
    skillArea: "grammar",
    builderKind: "grammar",
    baseLevel: "B1",
    supportObjective: "Reduce awkward sentence order.",
    categoryPath: ["Grammar", "Accuracy"],
    teachingSummary: "English word order carries meaning and emphasis, especially in questions, adverbs, and object placement.",
    whenToUse: "Use it whenever adverbs, objects, or question forms make a sentence feel unnatural.",
    whenNotToUse: "Do not mirror the order of another language when English expects a fixed pattern.",
    examples: [
      "I only realized the problem after I sent the message.",
      "Rarely do we see a change that quickly.",
      "She gave me the feedback in private.",
    ],
    commonMistakes: [
      "Placing adverbs in the wrong position.",
      "Using statement word order in a question.",
      "Breaking phrasal verbs with awkward object placement.",
    ],
    prerequisiteKeys: [],
    relatedKeys: ["articles", "connectors"],
  },
  {
    key: "hedging",
    title: "Hedging",
    family: "Register",
    description: "Sound precise and careful in opinions and argument.",
    skillArea: "vocabulary",
    builderKind: "grammar",
    baseLevel: "C1",
    supportObjective: "Improve nuance and academic tone.",
    categoryPath: ["Grammar", "Register"],
    teachingSummary: "Hedging makes a claim more precise, less absolute, and more credible in analytical writing.",
    whenToUse: "Use it when evidence is limited, claims are interpretive, or tone needs caution.",
    whenNotToUse: "Do not hedge simple facts so much that the sentence loses confidence.",
    examples: [
      "This may suggest that the policy needs revision.",
      "The result appears to be more limited than expected.",
      "It seems likely that the delay affected the final outcome.",
    ],
    commonMistakes: [
      "Making an analytical claim sound too absolute.",
      "Using too many hedges and weakening the sentence completely.",
      "Choosing a hedging verb that does not fit the evidence level.",
    ],
    prerequisiteKeys: ["modals", "connectors"],
    relatedKeys: ["opinion-verbs", "soften-a-claim", "academic-phrases"],
  },
  {
    key: "collocations",
    title: "Collocations",
    family: "Vocabulary in Use",
    description: "Choose words that naturally belong together.",
    skillArea: "vocabulary",
    builderKind: "vocabulary",
    baseLevel: "B1",
    supportObjective: "Sound more natural.",
    categoryPath: ["Vocabulary", "Natural Pairings"],
    teachingSummary: "Many natural English choices depend on word partnerships rather than grammar rules.",
    whenToUse: "Use collocations to make everyday and academic language sound automatic and native-like.",
    whenNotToUse: "Do not translate adjective-noun or verb-noun combinations literally.",
    examples: [
      "pay attention",
      "strong coffee",
      "make progress",
    ],
    commonMistakes: [
      "Choosing a dictionary-correct but unnatural verb.",
      "Building awkward adjective-noun pairs.",
      "Replacing a stable chunk with a literal translation.",
    ],
    prerequisiteKeys: [],
    relatedKeys: ["word-families", "spoken-chunks"],
  },
  {
    key: "opinion-verbs",
    title: "Opinion Verbs",
    family: "Vocabulary in Use",
    description: "Move beyond think by choosing verbs that fit certainty and register.",
    skillArea: "vocabulary",
    builderKind: "vocabulary",
    baseLevel: "B2",
    supportObjective: "Express opinion with more control.",
    categoryPath: ["Vocabulary", "Argument"],
    teachingSummary: "Opinion verbs shape how strong, cautious, academic, or personal a claim sounds.",
    whenToUse: "Use them in spoken opinions, essays, and explanations when think feels too basic.",
    whenNotToUse: "Do not use a strong verb like prove when the evidence only suggests a pattern.",
    examples: [
      "I would argue that short daily practice matters more.",
      "The evidence suggests a more limited effect.",
      "This result appears to challenge the earlier assumption.",
    ],
    commonMistakes: [
      "Using prove without strong evidence.",
      "Repeating think in every sentence.",
      "Choosing a verb with the wrong certainty level.",
    ],
    prerequisiteKeys: [],
    relatedKeys: ["hedging", "academic-phrases"],
  },
  {
    key: "word-families",
    title: "Word Families",
    family: "Vocabulary in Use",
    description: "Control noun, verb, adjective, and adverb forms around the same core meaning.",
    skillArea: "vocabulary",
    builderKind: "vocabulary",
    baseLevel: "B1",
    supportObjective: "Use the right form in the right sentence slot.",
    categoryPath: ["Vocabulary", "Word Choice"],
    teachingSummary: "Knowing a word family helps you shift meaning across sentence roles without sounding basic.",
    whenToUse: "Use it when you want to move between actions, qualities, and results precisely.",
    whenNotToUse: "Do not force a family member into a slot that needs a different form or register.",
    examples: [
      "improve / improvement / improved / progressively",
      "decide / decision / decisive / decisively",
      "analyze / analysis / analytical / analytically",
    ],
    commonMistakes: [
      "Using an adjective where a noun is needed.",
      "Misspelling a family member even when the root is known.",
      "Choosing a form that changes the meaning too much.",
    ],
    prerequisiteKeys: [],
    relatedKeys: ["collocations", "academic-phrases"],
  },
  {
    key: "work-study-vocabulary",
    title: "Work & Study Vocabulary",
    family: "Themes",
    description: "Use sharper language for tasks, deadlines, projects, and learning routines.",
    skillArea: "vocabulary",
    builderKind: "vocabulary",
    baseLevel: "B1",
    supportObjective: "Speak about goals and routines more precisely.",
    categoryPath: ["Vocabulary", "Themes"],
    teachingSummary: "Theme clusters help vocabulary stick because words keep returning in a shared context.",
    whenToUse: "Use it for workplace communication, study plans, tasks, feedback, and deadlines.",
    whenNotToUse: "Do not rely on vague verbs like do or make when a clearer work word exists.",
    examples: [
      "meet a deadline",
      "revise the draft",
      "fall behind on the schedule",
    ],
    commonMistakes: [
      "Using weak verbs for task language.",
      "Choosing words that fit school but not work, or the reverse.",
      "Repeating the same small group of basic nouns.",
    ],
    prerequisiteKeys: [],
    relatedKeys: ["collocations", "spoken-chunks"],
  },
  {
    key: "academic-precision",
    title: "Academic Precision",
    family: "Register",
    description: "Upgrade general words into more exact analytical vocabulary.",
    skillArea: "vocabulary",
    builderKind: "vocabulary",
    baseLevel: "C1",
    supportObjective: "Write with more precision and control.",
    categoryPath: ["Vocabulary", "Register"],
    teachingSummary: "Academic precision comes from better word choice, not just longer words.",
    whenToUse: "Use it in essays, reports, summaries, and analytical explanations.",
    whenNotToUse: "Do not choose formal vocabulary that makes a simple sentence stiff or unnatural.",
    examples: [
      "limited instead of small in analytical comparison",
      "indicate instead of show in formal explanation",
      "challenge instead of say against in argument",
    ],
    commonMistakes: [
      "Upgrading vocabulary without upgrading sentence logic.",
      "Using a formal word with the wrong collocation.",
      "Sounding abstract without becoming clearer.",
    ],
    prerequisiteKeys: ["opinion-verbs", "hedging"],
    relatedKeys: ["academic-phrases", "soften-a-claim"],
  },
  {
    key: "spoken-chunks",
    title: "Spoken Chunks",
    family: "Chunks",
    description: "Use ready-made spoken phrases that make conversation smoother.",
    skillArea: "vocabulary",
    builderKind: "phrase_idiom",
    baseLevel: "B1",
    supportObjective: "Sound more natural in spoken flow.",
    categoryPath: ["Phrases", "Chunks"],
    teachingSummary: "Spoken chunks reduce hesitation because meaning comes from a full phrase, not one word at a time.",
    whenToUse: "Use them to agree, soften, transition, react, or organize speech naturally.",
    whenNotToUse: "Do not overuse fillers until the sentence sounds empty or repetitive.",
    examples: [
      "To be honest, I expected a different result.",
      "At the same time, I can see why they chose it.",
      "That said, the final version still feels stronger.",
    ],
    commonMistakes: [
      "Forcing a spoken chunk into formal writing.",
      "Using the chunk as decoration instead of linking meaning.",
      "Choosing a filler where a stronger transition is needed.",
    ],
    prerequisiteKeys: [],
    relatedKeys: ["common-idioms", "connectors"],
  },
  {
    key: "academic-phrases",
    title: "Academic Phrases",
    family: "Chunks",
    description: "Use stable phrases for analysis, comparison, caution, and conclusion.",
    skillArea: "vocabulary",
    builderKind: "phrase_idiom",
    baseLevel: "B2",
    supportObjective: "Write more like a controlled analyst than a translator.",
    categoryPath: ["Phrases", "Academic"],
    teachingSummary: "Academic phrases give structure to formal writing when the logic is already clear.",
    whenToUse: "Use them to frame evidence, compare findings, soften claims, and conclude carefully.",
    whenNotToUse: "Do not stack formal phrases if the sentence underneath is still weak or unclear.",
    examples: [
      "This may indicate that...",
      "A possible explanation is that...",
      "In contrast, the second group showed...",
    ],
    commonMistakes: [
      "Using a phrase without the right evidence after it.",
      "Choosing a phrase that sounds too formal for the task.",
      "Writing templates instead of real analysis.",
    ],
    prerequisiteKeys: ["hedging", "opinion-verbs"],
    relatedKeys: ["academic-precision", "soften-a-claim"],
  },
  {
    key: "common-idioms",
    title: "Common Idioms",
    family: "Idioms",
    description: "Use high-value idioms when the context really supports them.",
    skillArea: "vocabulary",
    builderKind: "phrase_idiom",
    baseLevel: "B2",
    supportObjective: "Expand expressive range without sounding forced.",
    categoryPath: ["Phrases", "Idioms"],
    teachingSummary: "Idioms work when context, tone, and naturalness line up; they fail when used as decoration.",
    whenToUse: "Use them in spoken English or informal writing when tone allows a figurative phrase.",
    whenNotToUse: "Avoid them in formal analytical writing or when the literal meaning still confuses the idea.",
    examples: [
      "The team was back to square one.",
      "That comment hit the nail on the head.",
      "We had to think on our feet.",
    ],
    commonMistakes: [
      "Using an idiom in a context that sounds too formal.",
      "Mixing the words of the idiom and breaking it.",
      "Choosing an idiom that clouds the meaning.",
    ],
    prerequisiteKeys: ["spoken-chunks"],
    relatedKeys: ["spoken-chunks", "natural-collocations"],
  },
  {
    key: "natural-collocations",
    title: "Natural Collocations",
    family: "Chunks",
    description: "Train stable phrase partnerships that make your English sound less translated.",
    skillArea: "vocabulary",
    builderKind: "phrase_idiom",
    baseLevel: "B1",
    supportObjective: "Make phrase choices feel more automatic.",
    categoryPath: ["Phrases", "Chunks"],
    teachingSummary: "Chunk-level collocations help you produce faster because you retrieve a whole phrase together.",
    whenToUse: "Use them in everyday speaking and writing where naturalness matters more than complexity alone.",
    whenNotToUse: "Do not break a fixed phrase just because the individual words look correct.",
    examples: [
      "draw a conclusion",
      "raise a concern",
      "take responsibility",
    ],
    commonMistakes: [
      "Combining a good noun with the wrong verb.",
      "Using dictionary synonyms that break the phrase.",
      "Treating chunks like separate words under pressure.",
    ],
    prerequisiteKeys: ["collocations"],
    relatedKeys: ["spoken-chunks", "work-study-vocabulary"],
  },
  {
    key: "sentence-combining",
    title: "Sentence Combining",
    family: "Flow",
    description: "Turn short basic clauses into richer sentences.",
    skillArea: "sentence_building",
    builderKind: "sentence",
    baseLevel: "B1",
    supportObjective: "Raise sentence complexity.",
    categoryPath: ["Sentence", "Expansion"],
    teachingSummary: "Sentence combining turns isolated facts into connected ideas with rhythm and logic.",
    whenToUse: "Use it when short ideas need to sound more mature and less fragmented.",
    whenNotToUse: "Do not combine so much that the sentence becomes hard to follow.",
    examples: [
      "I practised every day, which made the routine easier to keep.",
      "The draft was clear, but it still felt too direct.",
      "Although the plan was simple, it solved the main problem.",
    ],
    commonMistakes: [
      "Joining clauses without a clear relation.",
      "Creating run-on sentences.",
      "Adding complexity without improving meaning.",
    ],
    prerequisiteKeys: ["connectors"],
    relatedKeys: ["relative-clauses", "expand-short-sentences"],
  },
  {
    key: "expand-short-sentences",
    title: "Expand Short Sentences",
    family: "Expansion",
    description: "Take a basic idea and add time, reason, contrast, or result.",
    skillArea: "sentence_building",
    builderKind: "sentence",
    baseLevel: "B1",
    supportObjective: "Move beyond one-clause answers.",
    categoryPath: ["Sentence", "Expansion"],
    teachingSummary: "A stronger sentence often comes from one extra layer of meaning, not from using harder words.",
    whenToUse: "Use it when your sentence is correct but too short, flat, or limited.",
    whenNotToUse: "Do not add random detail that does not support the main idea.",
    examples: [
      "I practice every day because short sessions are easier to sustain.",
      "The course helped me, especially when I had to write longer answers.",
      "We changed the plan, which reduced the pressure immediately.",
    ],
    commonMistakes: [
      "Adding detail that does not connect to the main point.",
      "Repeating the same idea with more words.",
      "Using a longer sentence that is still logically thin.",
    ],
    prerequisiteKeys: [],
    relatedKeys: ["sentence-combining", "clarity-and-emphasis"],
  },
  {
    key: "soften-a-claim",
    title: "Soften a Claim",
    family: "Tone",
    description: "Make a sentence more careful, balanced, and credible.",
    skillArea: "sentence_building",
    builderKind: "sentence",
    baseLevel: "B2",
    supportObjective: "Control analytical tone.",
    categoryPath: ["Sentence", "Tone"],
    teachingSummary: "A softer claim often sounds stronger because it matches the evidence instead of overstating it.",
    whenToUse: "Use it in analytical, reflective, or persuasive sentences where certainty should be limited.",
    whenNotToUse: "Do not soften a statement that is already a simple fact.",
    examples: [
      "This may suggest that the policy needs revision.",
      "The result appears to support the first explanation.",
      "It seems likely that routine matters more than intensity here.",
    ],
    commonMistakes: [
      "Using prove when suggest is enough.",
      "Stacking too many hedges into one weak sentence.",
      "Changing only one word while the tone stays absolute.",
    ],
    prerequisiteKeys: ["hedging", "opinion-verbs"],
    relatedKeys: ["hedging", "academic-phrases", "compare-contrast"],
  },
  {
    key: "clarity-and-emphasis",
    title: "Clarity & Emphasis",
    family: "Control",
    description: "Place the strongest idea where the sentence carries the most weight.",
    skillArea: "sentence_building",
    builderKind: "sentence",
    baseLevel: "B2",
    supportObjective: "Make sentences clearer and more deliberate.",
    categoryPath: ["Sentence", "Control"],
    teachingSummary: "Clarity depends on what the sentence foregrounds, delays, and ends with.",
    whenToUse: "Use it when a sentence is technically correct but still feels weak or messy.",
    whenNotToUse: "Do not move emphasis around without checking whether the logic still lands clearly.",
    examples: [
      "What matters most is not speed, but consistency.",
      "Only after the second review did the pattern become obvious.",
      "The strongest point in the report comes near the end.",
    ],
    commonMistakes: [
      "Burying the key idea in the middle of the sentence.",
      "Using fronted emphasis that sounds unnatural.",
      "Making the sentence more dramatic instead of more precise.",
    ],
    prerequisiteKeys: ["word-order"],
    relatedKeys: ["expand-short-sentences", "compare-contrast"],
  },
  {
    key: "compare-contrast",
    title: "Compare & Contrast",
    family: "Logic",
    description: "Balance two ideas without losing the relationship between them.",
    skillArea: "sentence_building",
    builderKind: "sentence",
    baseLevel: "B2",
    supportObjective: "Build more analytical comparisons.",
    categoryPath: ["Sentence", "Logic"],
    teachingSummary: "Comparison writing needs both content and the signal words that reveal the relationship cleanly.",
    whenToUse: "Use it when you need to show difference, similarity, trade-off, or tension between ideas.",
    whenNotToUse: "Do not compare two ideas if the sentence never explains the basis of comparison.",
    examples: [
      "The first draft was clearer, whereas the second sounded more natural.",
      "While the session was shorter, it was also more focused.",
      "Both options are useful, but they solve different problems.",
    ],
    commonMistakes: [
      "Using however where whereas fits better.",
      "Listing two ideas without making the contrast explicit.",
      "Repeating the same adjective instead of sharpening the contrast.",
    ],
    prerequisiteKeys: ["connectors", "sentence-combining"],
    relatedKeys: ["cause-and-effect", "clarity-and-emphasis"],
  },
  {
    key: "cause-and-effect",
    title: "Cause & Effect",
    family: "Logic",
    description: "Explain why something happened and what followed from it.",
    skillArea: "sentence_building",
    builderKind: "sentence",
    baseLevel: "B1",
    supportObjective: "Strengthen reason-result control.",
    categoryPath: ["Sentence", "Logic"],
    teachingSummary: "Cause-effect sentences become stronger when the relation is explicit and proportional.",
    whenToUse: "Use it when a claim needs a clear reason, outcome, or consequence.",
    whenNotToUse: "Do not use a cause-effect connector unless the relation is actually causal.",
    examples: [
      "Because the prompts were shorter, I stayed more consistent.",
      "The review queue grew, so I focused on recovery first.",
      "This routine worked well as a result of its simplicity.",
    ],
    commonMistakes: [
      "Treating sequence as cause.",
      "Using so to join two weakly related ideas.",
      "Repeating because without varying sentence form.",
    ],
    prerequisiteKeys: ["connectors"],
    relatedKeys: ["conditionals", "compare-contrast"],
  },
];

export function getStructureUnit(structureKey: string) {
  return structureCatalog.find((unit) => unit.key === structureKey);
}

export function getBuilderMeta(builderKind: BuilderKind) {
  return builderMeta[builderKind];
}

export function getTopicsByBuilder(builderKind: BuilderKind) {
  return structureCatalog.filter((topic) => topic.builderKind === builderKind);
}

export function getBuilderKinds() {
  return Object.keys(builderMeta) as BuilderKind[];
}

export function builderRouteSegment(builderKind: BuilderKind) {
  return builderKind === "phrase_idiom" ? "phrases" : builderKind;
}

export function builderKindFromSegment(segment: string) {
  if (segment === "phrases") {
    return "phrase_idiom" as const;
  }

  if (getBuilderKinds().includes(segment as BuilderKind)) {
    return segment as BuilderKind;
  }

  return null;
}
